# Site settings
title: Vim Tricks
email: hello@vimtricks.com
description: > # this means to ignore newlines until "baseurl:"
  Tricks, tips, plugins, and more the ViM editor.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://vimtricks.com" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Colin Bartlett"
author_thumbnail: "/assets/images/logo.png" # Author avatar
# Theme customization - please change from the defaults!
gems: [jekyll-paginate, jekyll-gravatar]
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#024600" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github:
    twitter:
    facebook:
    gplus:
    pinterest:

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: false

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-48498244-17
  google_webmaster_key: fV0OyZ7dRpA6RJEQqTfkniwRiae5mSyRRcj7zP4yFTA
# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

comments: false
